source 'http://rubygems.org'

gem 'rails', '3.0.4'
gem 'rake', '0.9.2'

gem 'haml', '3.0.25'
gem 'haml-rails'
gem 'will_paginate', '3.0.pre2'
gem 'mootools-rails', '~> 0.4'
gem 'friendly_id', '~> 3.1'
gem 'sqlite3', '1.3.3'
gem 'redcarpet'
gem 'albino'
gem 'nokogiri'
gem 'ancestry'
